# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import proto.insta_pb2 as insta__pb2


class InstaServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetProfiles = channel.unary_unary(
        '/insta.InstaService/GetProfiles',
        request_serializer=insta__pb2.ProfilesData.SerializeToString,
        response_deserializer=insta__pb2.ProfilesData.FromString,
        )


class InstaServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetProfiles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InstaServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetProfiles': grpc.unary_unary_rpc_method_handler(
          servicer.GetProfiles,
          request_deserializer=insta__pb2.ProfilesData.FromString,
          response_serializer=insta__pb2.ProfilesData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'insta.InstaService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
