# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: insta.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='insta.proto',
  package='insta',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0binsta.proto\x12\x05insta\"m\n\x04Post\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.insta.Post.StoryType\x12\x0c\n\x04link\x18\x02 \x01(\t\x12\x0f\n\x07inst_id\x18\x03 \x01(\t\"!\n\tStoryType\x12\t\n\x05PHOTO\x10\x00\x12\t\n\x05VIDEO\x10\x01\"e\n\x07Profile\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\nis_private\x18\x04 \x01(\x08\x12\x1a\n\x05posts\x18\x05 \x03(\x0b\x32\x0b.insta.Post\"0\n\x0cProfilesData\x12 \n\x08profiles\x18\x01 \x03(\x0b\x32\x0e.insta.Profile2G\n\x0cInstaService\x12\x37\n\x0bGetProfiles\x12\x13.insta.ProfilesData\x1a\x13.insta.ProfilesDatab\x06proto3'
)



_POST_STORYTYPE = _descriptor.EnumDescriptor(
  name='StoryType',
  full_name='insta.Post.StoryType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PHOTO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIDEO', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=98,
  serialized_end=131,
)
_sym_db.RegisterEnumDescriptor(_POST_STORYTYPE)


_POST = _descriptor.Descriptor(
  name='Post',
  full_name='insta.Post',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='insta.Post.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link', full_name='insta.Post.link', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inst_id', full_name='insta.Post.inst_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _POST_STORYTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=131,
)


_PROFILE = _descriptor.Descriptor(
  name='Profile',
  full_name='insta.Profile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='insta.Profile.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='insta.Profile.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='insta.Profile.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_private', full_name='insta.Profile.is_private', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='posts', full_name='insta.Profile.posts', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=234,
)


_PROFILESDATA = _descriptor.Descriptor(
  name='ProfilesData',
  full_name='insta.ProfilesData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profiles', full_name='insta.ProfilesData.profiles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=284,
)

_POST.fields_by_name['type'].enum_type = _POST_STORYTYPE
_POST_STORYTYPE.containing_type = _POST
_PROFILE.fields_by_name['posts'].message_type = _POST
_PROFILESDATA.fields_by_name['profiles'].message_type = _PROFILE
DESCRIPTOR.message_types_by_name['Post'] = _POST
DESCRIPTOR.message_types_by_name['Profile'] = _PROFILE
DESCRIPTOR.message_types_by_name['ProfilesData'] = _PROFILESDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Post = _reflection.GeneratedProtocolMessageType('Post', (_message.Message,), {
  'DESCRIPTOR' : _POST,
  '__module__' : 'insta_pb2'
  # @@protoc_insertion_point(class_scope:insta.Post)
  })
_sym_db.RegisterMessage(Post)

Profile = _reflection.GeneratedProtocolMessageType('Profile', (_message.Message,), {
  'DESCRIPTOR' : _PROFILE,
  '__module__' : 'insta_pb2'
  # @@protoc_insertion_point(class_scope:insta.Profile)
  })
_sym_db.RegisterMessage(Profile)

ProfilesData = _reflection.GeneratedProtocolMessageType('ProfilesData', (_message.Message,), {
  'DESCRIPTOR' : _PROFILESDATA,
  '__module__' : 'insta_pb2'
  # @@protoc_insertion_point(class_scope:insta.ProfilesData)
  })
_sym_db.RegisterMessage(ProfilesData)



_INSTASERVICE = _descriptor.ServiceDescriptor(
  name='InstaService',
  full_name='insta.InstaService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=286,
  serialized_end=357,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProfiles',
    full_name='insta.InstaService.GetProfiles',
    index=0,
    containing_service=None,
    input_type=_PROFILESDATA,
    output_type=_PROFILESDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSTASERVICE)

DESCRIPTOR.services_by_name['InstaService'] = _INSTASERVICE

# @@protoc_insertion_point(module_scope)
